[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
axum = { version = "0.8.1", default-features = false, features = [
    "tokio",
    "http1",
    "http2",
    "macros",
] }
tokio = { version = "1", default-features = false, features = [
    "rt-multi-thread",
    "sync",
    "net",
    "macros",
] }
blender = { path = "../blender" }
log = "0.4.25"
colog = "1.3.0"
maud = { version = "0.27.0", features = ["axum"] }
url = { version = "2.5.4", default-features = false }
color-eyre = "0.6.3"
chrono = { version = "0.4.39", default-features = false, features = [
    "clock",
    "serde",
] }
tower-http = { version = "0.6.2", features = ["fs"], default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
futures = { version = "0.3.31", default-features = false }
http = "1.2.0"
toml = "0.8.20"
eyre = "0.6.12"
