[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", default-features = false, features = [
    "tokio",
    "http1",
    "http2",
    "macros",
] }
tokio = { version = "1", default-features = false, features = [
    "rt-multi-thread",
    "sync",
    "net",
    "macros",
] }
blender = { path = "../blender" }
log = "0.4.25"
colog = "1.3.0"
